In [49]:
from random import choice 
from numpy import array, dot, random
import pylab
import matplotlib.pyplot as plt

In [50]:
unit_step = lambda x: 0 if x < 0 else 1

In [51]:
training_data = [ (array([0,0,1]), 0), (array([0,1,1]), 1), (array([1,0,1]), 1), (array([1,1,1]), 1), ]
training_data

[(array([0, 0, 1]), 0),
 (array([0, 1, 1]), 1),
 (array([1, 0, 1]), 1),
 (array([1, 1, 1]), 1)]

In [52]:
w = random.rand(3)

In [53]:
errors = [] 
eta = 0.2 
n = 100

In [54]:
for i in xrange(n): 
    x, expected = choice(training_data) 
    result = dot(w, x) 
    error = expected - unit_step(result) 
    errors.append(error) 
    w += eta * error * x

In [55]:
for x, _ in training_data: 
    result = dot(x, w) 
    print("{}: {} -> {}".format(x[:2], result, unit_step(result)))

[0 0]: -0.129564311496 -> 0
[0 1]: 0.769809181871 -> 1
[1 0]: 0.00863491927487 -> 1
[1 1]: 0.908008412642 -> 1


In [62]:
#from pylab import plot, ylim 
errors
ylim([-1,1]) 
plt.plot(errors)
plt.show()

In [59]:
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(0.0, 2.0, 0.01)
s = np.sin(2*np.pi*t)
plt.plot(t, s)

In [60]:
plt.xlabel('time (s)')
plt.ylabel('voltage (mV)')
plt.title('About as simple as it gets, folks')
plt.grid(True)
plt.savefig("test.png")
plt.show()